spring:
  datasource:
    url: jdbc:postgresql://ec2-23-23-93-255.compute-1.amazonaws.com:5432/d5t06k85ohsutd?user=zqrtvxhfqmdjft&password=5946f5d3a5434dc18a5fd32dc6759c9b62b37cb0e687cb7e1f80b27dbd09c7ba&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    #url: jdbc:postgresql://ec2-54-228-182-57.eu-west-1.compute.amazonaws.com:5432/d7lnt6ggk9rcbt?user=tkacgwphjmxbcr&password=7b30fa8db77649da5b55ee2cd64b3c4399ef8feebc020417391b05121563b024&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    #url: jdbc:postgresql://localhost:5432/test_NC_db_2?user=postgres&password=password
    tomcat:
      max-active: 5
      max-idle: 5
logging:
  level:
    com:
      overseer: debug